<?xml version="1.0"?>
<package format="2">

  <name>pairs_tf_estimator</name>
  <version>1.0.0</version>
  <description>The pairs_tf_estimator package</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cmake_modules</depend>
  <depend>rospy</depend>
  <depend>pairs_lib</depend>
  <depend>pairs_msgs</depend>
  <depend>pairs_modules_msgs</depend>

</package>
