<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>pairs_utils</name>

  <version>2.0.0</version>
  <description>PAIRS Utils</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>builtin_interfaces</depend>
  <depend>pairs_odometry_republisher</depend>
  <depend>pairs_tf_connector</depend>
  <depend>pairs_tf_mirror</depend>
  <depend>pairs_tf_reconfigure</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
